version: "3"

services:
  # PostgreSQL service.
  postgres:
    image: postgres:11.3
    restart: always
    environment:
      POSTGRES_USER: ark_auth
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # # Authentication service.
  # ark_auth:
  #   build: ark_auth
  #   depends_on:
  #     - postgres
  #   restart: always
  #   environment:
  #     DATABASE_URL: "postgres://ark_auth:guest@postgres:5432/ark_auth"
  #     DATABASE_CONNECTIONS: "10"
  #     SERVER_HOSTNAME: "ark_auth"
  #     SERVER_BIND: "0.0.0.0:9000"
  #   ports:
  #     - "9000:9000"
