version: "3"

services:
  # PostgreSQL with TimescaleDB extension service.
  # <https://www.postgresql.org/>
  # <https://www.timescale.com/>
  postgres:
    build: docker/postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # Prometheus service.
  # <https://prometheus.io/>
  prometheus:
    build: docker/prometheus
    restart: always
    network_mode: "host"
    ports:
      - "9090:9090"

  # Sso gRPC service.
  # <https://grpc.io/>
  sso_grpc:
    build: sso
    depends_on:
      - postgres
    restart: always
    network_mode: "host"
    environment:
      SSO_DATABASE_URL: "postgres://guest:guest@localhost:5432/sso"
      SSO_DATABASE_CONNECTIONS: "10"
      SSO_BIND: "0.0.0.0:7000"
      SSO_HTTP_BIND: "0.0.0.0:7010"
    ports:
      - "7000:7000"
      - "7010:7010"

  # Sso OpenAPI gateway service.
  # <https://github.com/grpc-ecosystem/grpc-gateway>
  # <https://grpc-ecosystem.github.io/grpc-gateway/>
  sso_openapi:
    build: sso_openapi
    restart: always
    network_mode: "host"
    environment:
      SSO_OPENAPI_GRPC: "localhost:7000"
      SSO_OPENAPI_BIND: "localhost:8000"
    ports:
      - "8000:8000"
