version: "3"

services:
  # PostgreSQL with TimescaleDB extension service.
  # <https://www.postgresql.org/>
  # <https://www.timescale.com/>
  postgres:
    build: docker/postgres
    image: sso_postgres:latest
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # Prometheus service.
  # <https://prometheus.io/>
  prometheus:
    build: docker/prometheus
    image: sso_prometheus:latest
    restart: always
    ports:
      - "9090:9090"

  # Sso gRPC service.
  sso_grpc:
    build: sso
    image: sso_grpc:latest
    depends_on:
      - postgres
    restart: always
    environment:
      # Database connection.
      SSO_DATABASE_URL: "postgres://guest:guest@postgres:5432/sso"
      SSO_DATABASE_CONNECTIONS: "10"
      # SMTP server transport.
      # SSO_SMTP_HOST: ""
      # SSO_SMTP_PORT: ""
      # SSO_SMTP_USER: ""
      # SSO_SMTP_PASSWORD: ""
    ports:
      - "7042:7042"
      - "7043:7043"

  # Sso OpenAPI gateway service.
  sso_openapi:
    build: sso_openapi
    image: sso_openapi:latest
    restart: always
    environment:
      # gRPC server URL.
      SSO_OPENAPI_GRPC_URL: "sso_grpc:7042"
    ports:
      - "8042:8042"
