# ```bash
# # Build all services.
# docker-compose build
#
# # Start services.
# docker-compose up [$service]
#
# # Stop/destroy services.
# docker-compose stop
# docker-compose down
# ```
version: "3"

services:
  # PostgreSQL.
  # <https://www.postgresql.org/>
  postgres:
    build: docker/postgres
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # Prometheus.
  # <https://prometheus.io/>
  prometheus:
    build: docker/prometheus
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.http.routers.prometheus.entrypoints=sso_entrypoint"
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"

  # Sso gRPC server.
  sso-grpc:
    build: docker/sso
    image: sso:latest
    depends_on:
      - postgres
    restart: always
    environment:
      RUST_BACKTRACE: "1"
      RUST_LOG: "info"
      # Postgres connection.
      SSO_POSTGRES_URL: "postgres://guest:guest@postgres:5432/sso"
      SSO_POSTGRES_CONNECTIONS: "10"
      # # SMTP server transport.
      # SSO_SMTP_HOST: ""
      # SSO_SMTP_PORT: ""
      # SSO_SMTP_USER: ""
      # SSO_SMTP_PASSWORD: ""
      # SMTP file transport.
      SSO_SMTP_FILE: "./tmp"
      # Pwned Passwords integration.
      SSO_PWNED_PASSWORDS: "true"
      # Traefik forward authentication integration.
      SSO_TRAEFIK: "true"
      # # Github OAuth2 support.
      # SSO_GITHUB_CLIENT_ID: ""
      # SSO_GITHUB_CLIENT_SECRET: ""
      # # Microsoft OAuth2 support.
      # SSO_MICROSOFT_CLIENT_ID: ""
      # SSO_MICROSOFT_CLIENT_SECRET: ""
    entrypoint: ["sso-grpc"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sso-grpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.sso-grpc.loadbalancer.server.port=7042"
      - "traefik.http.routers.sso-grpc.service=sso-grpc"
      - "traefik.http.routers.sso-grpc.entrypoints=sso_entrypoint"
      - "traefik.http.routers.sso-grpc.rule=PathPrefix(`/`)"
      # - "traefik.http.routers.sso-grpc.tls=true"
      - "traefik.http.routers.sso-grpc.middlewares=sso_grpc_forwardauth"
      - "traefik.http.middlewares.sso_grpc_forwardauth.forwardauth.address=http://sso-grpc:7043/hook/traefik/self"
      - "traefik.http.middlewares.sso_grpc_forwardauth.forwardauth.trustForwardHeader=false"
      - "traefik.http.middlewares.sso_grpc_forwardauth.forwardauth.authResponseHeaders=Grpc-Metadata-Sso-Key-Id,Grpc-Metadata-Sso-Service-Id,Grpc-Metadata-Sso-User-Key-Id,Grpc-Metadata-Sso-User-Id"

  # Sso OpenAPI server.
  sso-openapi:
    build: docker/sso
    image: sso:latest
    restart: always
    environment:
      # gRPC server URL.
      SSO_GRPC_URL: "sso-grpc:7042"
    entrypoint: ["sso-openapi"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.sso-openapi.loadbalancer.server.port=8042"
      - "traefik.http.routers.sso-openapi.service=sso-openapi"
      - "traefik.http.routers.sso-openapi.entrypoints=sso_entrypoint"
      - "traefik.http.routers.sso-openapi.rule=PathPrefix(`/api`)"
      # - "traefik.http.routers.sso-openapi.tls=true"
      - "traefik.http.routers.sso-openapi.middlewares=sso_openapi_stripprefix,sso_openapi_forwardauth"
      - "traefik.http.middlewares.sso_openapi_stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.sso_openapi_forwardauth.forwardauth.address=http://sso-grpc:7043/hook/traefik/self"
      - "traefik.http.middlewares.sso_openapi_forwardauth.forwardauth.trustForwardHeader=false"
      - "traefik.http.middlewares.sso_openapi_forwardauth.forwardauth.authResponseHeaders=Grpc-Metadata-Sso-Key-Id,Grpc-Metadata-Sso-Service-Id,Grpc-Metadata-Sso-User-Key-Id,Grpc-Metadata-Sso-User-Id"

  # Traefik.
  # <https://docs.traefik.io/>
  traefik:
    image: traefik:latest
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./docker/build/cert:/cert"
      - "./docker/traefik:/etc/traefik"

networks:
  default:
    external:
      name: compose
