[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--write-mode=overwrite"]

[tasks.lint]
install_crate = "clippy"
command = "cargo"
args = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.manual]
script = [
    "pandoc manual2/user.md -f markdown -t html -s -o target/user-manual.html",
    "pandoc manual2/developer.md -f markdown -t html -s -o target/developer-manual.html"
]
