[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.lint]
workspace = false
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]

[tasks.manual]
script = [
    "mkdir -p target",
    "pandoc manual2/user/*.md -f markdown -t html -s --toc --toc-depth=5 -o target/user-manual.html",
    "pandoc manual2/developer/*.md -f markdown -t html -s --toc --toc-depth=5 -o target/developer-manual.html"
]
