[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.lint]
workspace = false
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.postgres-migrations]
workspace = false
script = [
    "(cd ark_auth && DATABASE_URL=\"postgres://guest:guest@postgres:5432/ark_auth\" diesel database reset --migration-dir migrations/postgres)",
]

[tasks.sqlite-migrations]
workspace = false
script = [
    "(cd ark_auth && DATABASE_URL=\"db.sqlite3\" diesel database reset --migration-dir migrations/sqlite)",
    "(cd ark_kv && DATABASE_URL=\"db.sqlite3\" diesel database reset --migration-dir migrations/sqlite)",
]

[tasks.build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test"]

[tasks.test-integration]
workspace = false
command = "cargo"
args = ["test", "--", "--ignored"]

[tasks.manual]
workspace = false
script = [
    "pandoc docs/ark_auth/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=docs/asset/pandoc.css --output=docs/ark_auth.html",
]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]
