[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.lint]
workspace = false
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.postgres-migrations]
script = [
    "(cd ark_auth && diesel database reset --migration-dir migrations/postgres)",
]

[tasks.sqlite-migrations]
script = [
    "(cd ark_auth && DATABASE_URL=\"db.sqlite3\" diesel database reset --migration-dir migrations/sqlite)",
]

[tasks.build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test"]

[tasks.manual]
script = [
    "pandoc docs/user/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=docs/asset/pandoc.css --output=docs/user.html",
    "pandoc docs/developer/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=docs/asset/pandoc.css --output=docs/developer.html"
]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]
