# Default targets:
# - clean
# - clippy
# - format (fmt)
# - check

[tasks.postgres-migrations]
workspace = false
script = [
    "(cd ark_auth && DATABASE_URL=\"postgres://ark_auth:guest@localhost:5432/ark_auth\" diesel database reset --migration-dir migrations/postgres)",
]

[tasks.sqlite-migrations]
workspace = false
script = [
    "(cd ark_auth && DATABASE_URL=\"db.sqlite3\" diesel database reset --migration-dir migrations/sqlite)",
    "(cd ark_kv && DATABASE_URL=\"db.sqlite3\" diesel database reset --migration-dir migrations/sqlite)",
]

[tasks.manual]
workspace = false
script = [
    "pandoc docs/ark_auth/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=docs/pandoc.css --output=docs/ark_auth.html",
]

[tasks.build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.test]
workspace = false
command = "cargo"
args = ["test"]
dependencies = ["format"]

[tasks.test-integration]
workspace = false
command = "cargo"
args = ["test", "--", "--ignored"]
dependencies = ["format"]

[tasks.doc]
workspace = false
command = "cargo"
args = ["doc", "--no-deps", "--open"]
dependencies = ["format"]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]
dependencies = ["format"]

[tasks.release-flow]
workspace = false
dependencies = ["manual", "test", "doc", "release"]
