[tasks.clean]
workspace = false
command = "cargo"
args = ["clean"]

[tasks.build]
workspace = false
command = "cargo"
args = ["build"]
dependencies = ["format"]

[tasks.lint]
workspace = false
command = "cargo"
args = ["clippy"]
dependencies = ["format"]

[tasks.release]
workspace = false
command = "cargo"
args = ["build", "--release"]

[tasks.manual]
script = [
    "pandoc manual/user/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=manual/asset/pandoc.css --output=manual/user.html",
    "pandoc manual/developer/*.md -f markdown --to=html5 --self-contained --toc --toc-depth=6 --css=manual/asset/pandoc.css --output=manual/developer.html"
]
