site_name: sso-v0.10.0
site_url: https://mojzu.net/sso/
repo_url: https://github.com/mojzu/sso
site_author: "Sam Ward"
copyright: Unlicense
docs_dir: docs-src
site_dir: docs
dev_addr: 0.0.0.0:8000
nav:
  - index.md
  - Guides:
      - guide/quickstart.md
      - guide/login.md
      - guide/register.md
      - guide/reset-password.md
      - guide/update-email.md
      - guide/update-password.md
      - guide/api-key.md
      - guide/oauth2-login.md
      - guide/csrf.md
      - guide/totp.md
      - guide/cli.md
      - guide/deployment.md
  - Changelog:
      - changelog/0.11.0.md
      - changelog/0.10.0.md
      - changelog/0.9.0.md
      - changelog/0.8.0.md
      - changelog/0.7.0.md
      - changelog/0.6.0.md
      - changelog/0.5.0.md
      - changelog/0.4.0.md
      - changelog/0.3.0.md
      - changelog/0.2.0.md
      - changelog/0.1.0.md
  - Developer:
      - developer/design.md
      - developer/developer.md
      - developer/reference.md
theme: readthedocs
