[package]
name = "hyper_openapi"
version = "0.1.0"
authors = ["Sam Ward <git@mojzu.net>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
hyper = "= 0.13.0-alpha.4"
mime = "0.3.14"
tokio = "= 0.2.0-alpha.6"
