version: "3"

services:
  # PostgreSQL service.
  postgres:
    image: postgres:11.3
    restart: always
    environment:
      POSTGRES_USER: sso
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # # Authentication service.
  # sso:
  #   build: sso
  #   depends_on:
  #     - postgres
  #   restart: always
  #   environment:
  #     DATABASE_URL: "postgres://sso:guest@postgres:5432/sso"
  #     DATABASE_CONNECTIONS: "10"
  #     SERVER_HOSTNAME: "sso"
  #     SERVER_BIND: "0.0.0.0:9000"
  #   ports:
  #     - "9000:9000"
