version: "3"

services:
  # PostgreSQL with TimescaleDB extension service.
  # <https://www.postgresql.org/>
  # <https://www.timescale.com/>
  postgres:
    build: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    ports:
      - "5432:5432"

  # # Prometheus service.
  # # <https://prometheus.io/>
  # prometheus:
  #   build: prometheus
  #   restart: always
  #   network_mode: "host"
  #   ports:
  #     - "9090:9090"

  # # Single sign-on service.
  # sso:
  #   build: sso
  #   depends_on:
  #     - postgres
  #   restart: always
  #   environment:
  #     DATABASE_URL: "postgres://guest:guest@postgres:5432/sso"
  #     DATABASE_CONNECTIONS: "10"
  #     SERVER_HOSTNAME: "sso"
  #     SERVER_BIND: "0.0.0.0:9000"
  #   ports:
  #     - "9000:9000"
