[package]
name = "sso"
version = "0.10.0"
description = "Single sign-on authentication server."
authors = ["Sam Ward <git@mojzu.net>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://mojzu.net/sso/"
documentation = "https://docs.rs/crate/sso/"
repository = "https://github.com/mojzu/sso"
categories = ["authentication", "web-programming", "command-line-utilities"]
edition = "2018"

[lib]
name = "sso"
path = "src/lib.rs"

[[bin]]
name = "sso-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "sso-grpc"
path = "src/bin/grpc.rs"

[features]
default = ["postgres"]
postgres = []

[dependencies]
clap = "2.33.0"
chrono = { version = "0.4.10", features = ["serde"] }
chrono-tz = "0.5.1"
diesel = { version = "1.4.3", features = ["postgres", "r2d2", "chrono", "serde_json", "uuidv07"] }
diesel_migrations = { version = "1.4.0", features = ["postgres"] }
env_logger = "0.6.2"
failure = "0.1.6"
handlebars = "2.0.4"
jsonwebtoken = "7.0.1"
lazy_static = "1.4.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
libreauth = "0.12.0"
log = { version = "0.4.8", features = ["max_level_trace", "release_max_level_info"] }
native-tls = "0.2.3"
prometheus = { version = "0.7.0", features = ["default", "process"] }
r2d2 = "0.8.8"
reqwest = { version = "0.10.1", features = ["json", "rustls-tls"] }
rustls = "0.16.0"
oauth2 = "=3.0.0-alpha.9"
sentry = "0.17.0"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.47"
serde_urlencoded = "0.6.1"
sha-1 = "0.8.2"
unic-langid = "0.7.1"
url = "2.1.1"
uuid = { version = "0.7.4", features = ["v4", "serde"] }
validator = "0.10.0"
zxcvbn = "2.0.1"

bytes = "0.4.12"
futures-util = "0.3"
http = "0.2"
http-body = "0.3.1"
hyper = "0.13"
prost = "0.6.1"
prost-derive = "0.6"
prost-types = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "signal", "fs", "macros", "uds"] }
tonic = { version = "0.1", features = ["tls"] }
tower-service = "0.3"

[build-dependencies]
tonic-build = "0.1"
