[package]
name = "sso"
version = "0.9.0"
description = "Single sign-on authentication server."
authors = ["Sam Ward <git@mojzu.net>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://mojzu.net/sso/"
documentation = "https://docs.rs/crate/sso/"
repository = "https://github.com/mojzu/sso"
categories = ["authentication", "web-programming::http-server", "command-line-utilities"]
edition = "2018"

[features]
default = ["postgres", "async_client", "sync_client"]
postgres = []
sqlite = []
async_client = []
sync_client = []

[dependencies]
actix = "0.8.3"
actix-identity = "0.1.0"
actix-rt = "0.2.6"
actix-service = "0.4.2"
actix-web = { version = "1.0.9", features = ["rust-tls"] }
clap = "2.33.0"
chrono = { version = "0.4.10", features = ["serde"] }
chrono-tz = "0.5.1"
derive_builder = "0.9.0"
diesel = { version = "1.4.3", features = ["postgres", "sqlite", "r2d2", "chrono", "serde_json", "uuidv07"] }
diesel_migrations = { version = "1.4.0", features = ["postgres", "sqlite"] }
env_logger = "0.7.1"
failure = "0.1.6"
futures = "0.1.29"
handlebars = "2.0.2"
http = "0.1.19"
job_scheduler = "1.1.0"
jsonwebtoken = "6.0.1"
lazy_static = "1.4.0"
lettre = "0.9.2"
lettre_email = "0.9.2"
libreauth = "0.12.0"
log = { version = "0.4.8", features = ["max_level_trace", "release_max_level_info"] }
native-tls = "0.2.3"
prometheus = "0.7.0"
r2d2 = "0.8.7"
reqwest = { version = "0.9.19", features = ["rustls-tls"] }
rustls = "0.15.2"
oauth2 = "= 3.0.0-alpha.3"
sentry = "0.17.0"
sentry-actix = "0.17.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
serde_qs = "0.5.1"
sha-1 = "0.8.1"
sysinfo = "0.9.6"
unic-langid = "0.7.1"
url = "1.7.2"
uuid = { version = "0.7.4", features = ["v4", "serde"] }
validator = "0.10.0"
validator_derive = "0.10.0"
zxcvbn = "2.0.0"
