[package]
name = "sso"
version = "0.10.0"
description = "Single sign-on authentication server."
authors = ["Sam Ward <git@mojzu.net>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://mojzu.net/sso/"
documentation = "https://docs.rs/crate/sso/"
repository = "https://github.com/mojzu/sso"
categories = ["authentication", "web-programming", "command-line-utilities"]
edition = "2018"

[lib]
name = "sso"
path = "src/lib.rs"

[[bin]]
name = "sso-cli"
path = "src/bin/cli.rs"

[[bin]]
name = "sso-grpc"
path = "src/bin/grpc.rs"

[features]
default = ["postgres"]
postgres = []

[dependencies]
clap = "2.33"
chrono = { version = "0.4", features = ["serde"] }
chrono-tz = "0.5"
diesel = { version = "1.4", features = ["postgres", "r2d2", "chrono", "serde_json", "uuidv07"] }
diesel_migrations = { version = "1.4", features = ["postgres"] }
env_logger = "0.7"
failure = "0.1"
handlebars = "3.0"
jsonwebtoken = "7.0"
lazy_static = "1.4"
lettre = "0.9"
lettre_email = "0.9"
libreauth = "0.13"
log = { version = "0.4", features = ["max_level_trace", "release_max_level_info"] }
native-tls = "0.2"
prometheus = { version = "0.8", features = ["default", "process"] }
r2d2 = "0.8"
reqwest = { version = "0.10", features = ["json", "rustls-tls"] }
rustls = "0.17"
oauth2 = "=3.0.0-alpha.9"
sentry = { version = "0.18", features = ["with_env_logger"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.6"
sha-1 = "0.8"
unic-langid = "0.8"
url = "2.1"
uuid = { version = "0.7.4", features = ["v4", "serde"] }
validator = "0.10"
zxcvbn = "2.0"

bytes = "0.4.12"
futures-util = "0.3"
http = "0.2"
http-body = "0.3"
hyper = "0.13"
prost = "0.6"
prost-derive = "0.6"
prost-types = "0.6"
tokio = { version = "0.2", features = ["rt-threaded", "time", "stream", "signal", "fs", "macros", "uds"] }
tonic = { version = "0.1", features = ["tls"] }
tower-service = "0.3"

[build-dependencies]
tonic-build = "0.1"
