[book]
title = "Ark Auth Manual"
authors = ["Sam Ward"]
multilingual = false
src = "md"

[build]
build-dir = "../docs"
create-missing = true
preprocess = ["links", "index"]

[output.html]
theme = "theme"
