[package]
name = "manual"
version = "0.1.0"
authors = ["Sam Ward <mail@mojzu.net>"]
edition = "2018"
publish = false
build = "build.rs"

[build-dependencies]
skeptic = "*"

[dependencies]
actix-rt = "*"
actix-web = { version = "^1.0.2", features = ["ssl", "client"] }
ark_auth = { path = "../ark_auth" }
chrono = { version = "*", features = ["serde"] }
futures = "*"
reqwest = "*"
serde_json = "*"
skeptic = "*"
uuid = { version = "*", features = ["v4"] }
