[package]
name = "ark_auth_manual"
version = "0.1.0"
authors = ["Sam Ward <mail@mojzu.net>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
skeptic = "0.13"

[dev-dependencies]
skeptic = "0.13"
