# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert.rules.yml"

# Scrape metrics endpoints configuration.
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "sso"
    metrics_path: "/v1/metrics"
    bearer_token: "4KYG4LFV2UGWKC3FYWXNRQMX4FBBBJM6CI"
    static_configs:
      - targets: ["localhost:9000"]
