[package]
name = "ark_auth"
version = "0.2.0"
description = "Authentication server"
authors = ["Sam Ward <mail@mojzu.net>"]
license = "Unlicense"
readme = "README.md"
homepage = "https://mojzu.net/ark_auth/"
repository = "https://github.com/mojzu/ark_auth"
edition = "2018"

[features]
default = ["postgres"]
postgres = []
sqlite = []

[dependencies]
actix = "*"
actix-http = "*"
actix-rt = "*"
actix-service = "*"
actix-web = { version = "*", features = ["ssl", "client"] }
bcrypt = "*"
clap = "*"
chrono = { version = "*", features = ["serde"] }
diesel = { version = "*", features = ["postgres", "sqlite", "r2d2", "chrono", "serde_json"] }
diesel_migrations = { version = "*", features = ["postgres", "sqlite"] }
env_logger = "*"
failure = "*"
futures = "*"
jsonwebtoken = "*"
lettre = "*"
lettre_email = "*"
log = { version = "*", features = ["max_level_trace", "release_max_level_info"] }
native-tls = "*"
r2d2 = "*"
oauth2 = "2.0.0-beta.2"
sentry = "*"
sentry-actix = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
sha-1 = "*"
url = "*"
uuid = { version = "*", features = ["v4"] }
time = "*"
validator = "*"
validator_derive = "*"
zxcvbn = "*"
